<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>ML and DL</b></center>

<center><b><h1>Lab - 6</b></center>    
<pre>    

# Decision Tree Classifier

In [96]:
from sklearn.datasets import load_iris 

# Import iris data ser using sklearn

In [98]:
data = load_iris()

In [99]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

# Importing the libraries

In [101]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree

# Divide the data into input and output

In [103]:
x = data['data']

In [104]:
y = data['target']

In [105]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Splitting the dataset into the Training set and Test set

In [107]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42, stratify=y)


# Fitting DecisionTreeClassifier   on dataset

In [109]:
model = DecisionTreeClassifier()

In [110]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

# Display Decision Tree

In [112]:
%matplotlib qt

In [113]:
tree.plot_tree(model)

[Text(0.3181818181818182, 0.9166666666666666, 'x[2] <= 2.45\ngini = 0.667\nsamples = 100\nvalue = [34, 33, 33]'),
 Text(0.22727272727272727, 0.75, 'gini = 0.0\nsamples = 34\nvalue = [34, 0, 0]'),
 Text(0.2727272727272727, 0.8333333333333333, 'True  '),
 Text(0.4090909090909091, 0.75, 'x[3] <= 1.55\ngini = 0.5\nsamples = 66\nvalue = [0, 33, 33]'),
 Text(0.36363636363636365, 0.8333333333333333, '  False'),
 Text(0.18181818181818182, 0.5833333333333334, 'x[2] <= 4.95\ngini = 0.061\nsamples = 32\nvalue = [0, 31, 1]'),
 Text(0.09090909090909091, 0.4166666666666667, 'gini = 0.0\nsamples = 31\nvalue = [0, 31, 0]'),
 Text(0.2727272727272727, 0.4166666666666667, 'gini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.6363636363636364, 0.5833333333333334, 'x[3] <= 1.7\ngini = 0.111\nsamples = 34\nvalue = [0, 2, 32]'),
 Text(0.45454545454545453, 0.4166666666666667, 'x[2] <= 5.45\ngini = 0.5\nsamples = 2\nvalue = [0, 1, 1]'),
 Text(0.36363636363636365, 0.25, 'gini = 0.0\nsamples = 1\nvalue = [0, 1,

In [114]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])?  n


Nothing done.


In [115]:
%whos

Variable                 Type                      Data/Info
------------------------------------------------------------
DecisionTreeClassifier   ABCMeta                   <class 'sklearn.tree._cla<...>.DecisionTreeClassifier'>
cols                     Index                     Index(['Age', 'BMI', 'Blo<...>],\n      dtype='object')
data                     Bunch                     {'data': array([[5.1, 3.5<...> 'sklearn.datasets.data'}
dataframe_columns        function                  <function dataframe_colum<...>ns at 0x0000028CCD7FF880>
dataframe_hash           function                  <function dataframe_hash at 0x0000028CCD7FD760>
df                       DataFrame                      Pregnancies  Glucose<...>n\n[768 rows x 9 columns]
dtypes_str               function                  <function dtypes_str at 0x0000028CCD7FE7A0>
file                     BufferedReader            <_io.BufferedReader name='model.pkl'>
get_dataframes           function                  <function

# Predict the x_test 

In [117]:
model.predict(x_test)

array([2, 1, 0, 1, 2, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 2, 2, 1, 2, 1, 2, 1,
       0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 0, 1, 0, 0, 2, 1, 2, 1, 1, 1, 0, 0,
       2, 1, 2, 2, 1, 2])

In [118]:
y_test

array([2, 1, 0, 1, 2, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 2, 2, 1, 2, 1, 2, 1,
       0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 0, 1, 0, 0, 2, 1, 1, 1, 1, 1, 0, 0,
       2, 1, 2, 2, 1, 2])

In [119]:
model.score(x_train,y_train)

1.0

In [120]:
model.score(x_test,y_test)

0.98

# Import diabetes.csv dataset 

In [122]:
df = pd.read_csv("diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age       Outcome  
0                       0.627   50      Diabetic  
1                       0.351   31  Non Diabetic  
2                       0.672   32      Diabetic  
3                       0.167   21  Non Diabetic  
4                       2.288   33      Diabetic  
..                        ...  ...           ...  
763                     0.171   63  Non Diabetic  
764                     0.340   27  Non Diabetic  
765                     0.245   30  Non Diabetic  
766                     0.349   47      Diabetic  
767                     0.315   23  Non Diabetic  

[768 rows x 9 columns]

# Check the distribution of the target

In [124]:
df['Outcome'].value_counts()

Outcome
Non Diabetic    500
Diabetic        268
Name: count, dtype: int64

# Replace zeros with NaN for specific columns

In [126]:
df = df.apply(lambda x: x if x.name == 'Pregnancies' else x.replace(0, np.nan))

In [127]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0      NaN  33.6   
1              1     85.0           66.0           29.0      NaN  26.6   
2              8    183.0           64.0            NaN      NaN  23.3   
3              1     89.0           66.0           23.0     94.0  28.1   
4              0    137.0           40.0           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0           76.0           48.0    180.0  32.9   
764            2    122.0           70.0           27.0      NaN  36.8   
765            5    121.0           72.0           23.0    112.0  26.2   
766            1    126.0           60.0            NaN      NaN  30.1   
767            1     93.0           70.0           31.0      NaN  30.4   

     DiabetesPedigreeFunction  Age       Outcome  
0                       0.627   50      Diabetic  
1                       0.351   31  Non Diabetic  
2                       0.672   32      Diabetic  
3                       0.167   21  Non Diabetic  
4                       2.288   33      Diabetic  
..                        ...  ...           ...  
763                     0.171   63  Non Diabetic  
764                     0.340   27  Non Diabetic  
765                     0.245   30  Non Diabetic  
766                     0.349   47      Diabetic  
767                     0.315   23  Non Diabetic  

[768 rows x 9 columns]

# Check for missing values

In [129]:
df.isnull().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

# Fill missing values with median

In [131]:
medi_pre, medi_gluc, medi_bp, medi_skin, medi_ins, medi_bmi = df['Pregnancies'].median(), df['Glucose'].median(), df['BloodPressure'].median(), df['SkinThickness'].median(), df['Insulin'].median(), df['BMI'].median()

In [200]:
df['Pregnancies'].fillna(medi_pre, inplace=True)
df['Glucose'].fillna(medi_gluc, inplace=True)
df['BloodPressure'].fillna(medi_bp, inplace=True)
df['SkinThickness'].fillna(medi_skin, inplace=True)
df['Insulin'].fillna(medi_ins, inplace=True)
df['BMI'].fillna(medi_bmi, inplace=True)

C:\Users\ayush\AppData\Local\Temp\ipykernel_18900\94895953.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Pregnancies'].fillna(medi_pre, inplace=True)
C:\Users\ayush\AppData\Local\Temp\ipykernel_18900\94895953.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example

In [202]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

# Visualize Distributions

In [205]:
import seaborn as sb
sb.pairplot(df, hue='Outcome')

# Convert Targer data into interger code

In [207]:
df['Outcome'] = df['Outcome'].map({"Diabetic":1,"Non Diabetic":0})

In [209]:
sb.heatmap(df.corr(), annot = True, cmap='coolwarm')
plt.show()

In [211]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0    125.0  33.6   
1              1     85.0           66.0           29.0    125.0  26.6   
2              8    183.0           64.0           29.0    125.0  23.3   
3              1     89.0           66.0           23.0     94.0  28.1   
4              0    137.0           40.0           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0           76.0           48.0    180.0  32.9   
764            2    122.0           70.0           27.0    125.0  36.8   
765            5    121.0           72.0           23.0    112.0  26.2   
766            1    126.0           60.0           29.0    125.0  30.1   
767            1     93.0           70.0           31.0    125.0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

# Divide the data into input and output

In [213]:
X = df.drop('Outcome', axis=1)


In [217]:
y = df['Outcome']

# Splitting the dataset into the Training set and Test set

In [219]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=2)

# Create Model

In [221]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(random_state=42, max_depth=100)

# Fitting DecisionTreeClassifier   on dataset

In [224]:
model.fit(X_train, y_train)


DecisionTreeClassifier(max_depth=100, random_state=42)

# Display Decision Tree

In [226]:

%matplotlib qt
tree.plot_tree(model)

[Text(0.5137451171875, 0.96875, 'x[1] <= 127.5\ngini = 0.461\nsamples = 514\nvalue = [329, 185]'),
 Text(0.209765625, 0.90625, 'x[7] <= 28.5\ngini = 0.315\nsamples = 316\nvalue = [254.0, 62.0]'),
 Text(0.36175537109375, 0.9375, 'True  '),
 Text(0.1125, 0.84375, 'x[5] <= 45.4\ngini = 0.158\nsamples = 173\nvalue = [158, 15]'),
 Text(0.1, 0.78125, 'x[5] <= 30.9\ngini = 0.131\nsamples = 170\nvalue = [158, 12]'),
 Text(0.0875, 0.71875, 'gini = 0.0\nsamples = 94\nvalue = [94, 0]'),
 Text(0.1125, 0.71875, 'x[6] <= 1.272\ngini = 0.266\nsamples = 76\nvalue = [64, 12]'),
 Text(0.1, 0.65625, 'x[5] <= 33.7\ngini = 0.25\nsamples = 75\nvalue = [64, 11]'),
 Text(0.0625, 0.59375, 'x[1] <= 118.5\ngini = 0.393\nsamples = 26\nvalue = [19, 7]'),
 Text(0.05, 0.53125, 'x[5] <= 33.45\ngini = 0.33\nsamples = 24\nvalue = [19, 5]'),
 Text(0.025, 0.46875, 'x[2] <= 53.0\ngini = 0.245\nsamples = 21\nvalue = [18, 3]'),
 Text(0.0125, 0.40625, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.0375, 0.40625, 'x[5] <

# Predict the x_test 

In [228]:
y_pred = model.predict(X_test)


# Display Training Accuracy

In [230]:
model.score(X_train, y_train)


1.0

# Display Test Accuracy

In [232]:
model.score(X_test, y_test)


0.6850393700787402

# Confusion Matrix

In [234]:
from sklearn.metrics import confusion_matrix, classification_report


In [236]:
print(confusion_matrix(y_test, y_pred))


[[132  39]
 [ 41  42]]


In [238]:

from sklearn.metrics import classification_report, roc_auc_score, accuracy_score
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.76      0.77      0.77       171
           1       0.52      0.51      0.51        83

    accuracy                           0.69       254
   macro avg       0.64      0.64      0.64       254
weighted avg       0.68      0.69      0.68       254



# Save Model State

In [145]:
import pickle

In [240]:
with open('model.pkl','wb') as file:
    pickle.dump(model, file)
print("Model Saved")


Model Saved


# Load Model from Disk

In [148]:
with open('model.pkl','rb') as file:
    loaded_model = pickle.load(file)

In [149]:
loaded_model.predict(x_test)

array([2, 1, 0, 1, 2, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 2, 2, 1, 2, 1, 2, 1,
       0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 0, 1, 0, 0, 2, 1, 2, 1, 1, 1, 0, 0,
       2, 1, 2, 2, 1, 2])